import type { WorkspaceState } from './types'

export const mockState: WorkspaceState = {
  dir: '/Users/yeemio/myproject/.owlscale',
  pending_review: 2,
  agent_policy: null,
  agents: [
    { id: 'cc', name: 'Claude Code', role: 'coordinator' },
    { id: 'copilot', name: 'GitHub Copilot', role: 'executor' },
    { id: 'codex', name: 'Codex CLI', role: 'executor' },
  ],
  worktrees: [
    {
      id: 'coding-implement-auth',
      path: '/Users/yeemio/.owlscale-worktrees/myproject/coding-implement-auth',
      branch: 'owlscale/implement-auth',
      type: 'coding',
      agent_id: 'copilot',
      status: 'ready',
    },
    {
      id: 'review-implement-auth',
      path: '/Users/yeemio/.owlscale-worktrees/myproject/review-implement-auth',
      branch: 'owlscale/implement-auth-review',
      type: 'review',
      agent_id: null,
      status: 'ready',
    },
  ],
  tasks: [
    {
      id: 'implement-auth',
      status: 'returned',
      assignee: 'copilot',
      goal: 'Add JWT authentication to the API',
      worktree_id: 'coding-implement-auth',
      review_worktree_id: 'review-implement-auth',
      review_worktree_ready: true,
      review_owner_id: null,
      coding_worktree_assigned: true,
      coding_worktree_missing: false,
      ownership_override: false,
    },
    {
      id: 'fix-login-bug',
      status: 'returned',
      assignee: 'codex',
      goal: 'Fix session expiry not clearing cookie',
      worktree_id: null,
      review_worktree_id: null,
      review_worktree_ready: false,
      review_owner_id: null,
      coding_worktree_assigned: false,
      coding_worktree_missing: false,
      ownership_override: false,
    },
    {
      id: 'add-rate-limiting',
      status: 'dispatched',
      assignee: 'copilot',
      goal: 'Add rate limiting middleware',
      worktree_id: null,
      review_worktree_id: null,
      review_worktree_ready: false,
      review_owner_id: null,
      coding_worktree_assigned: false,
      coding_worktree_missing: false,
      ownership_override: false,
    },
    {
      id: 'write-api-docs',
      status: 'accepted',
      assignee: 'cc',
      goal: 'Document all REST endpoints',
      worktree_id: null,
      review_worktree_id: null,
      review_worktree_ready: false,
      review_owner_id: null,
      coding_worktree_assigned: false,
      coding_worktree_missing: false,
      ownership_override: false,
    },
  ],
}
